### ISSUE TITLE
Add support for hardware transcoding

### ISSUE THREAD

**Issue by paulroche** [cturra/docker-plexmediaserver#14]
plex alpha beta adds hardware transcoding if your server supports it, however to run from docker we need to allow /dev/dri

https://forums.plex.tv/discussion/comment/1334624/#Comment_1334624
https://forums.plex.tv/discussion/250946/plex-media-server-hardware-transcoding-preview-closed/p1

**Comment by cturra** [comment]
thanks for the suggestion!

i've started pulling together a branch to explicitly add support for this, which can be found in the [hardware-transcoding](https://github.com/cturra/docker-plexmediaserver/tree/hardware-transcoding) branch.

until this is merged, you should be able to use the `DOCKER_OPTS` parameter in the `vars` file to pass through the device mapping. would look like:

```
DOCKER_OPTS="--device=/dev/dri:/dev/dri"
```

any assistance in testing this would be awesome!

**Comment by cturra** [comment]
update: at the time of writing this, the plex build that includes hardware transcoding support is `1.8.1-4140` which is in beta and not available on the public or plexpass channels. you can get this specific build by running the container with the following in your `vars` file:

```
PLEX_SERVER_VERSION=1.8.1.4140-82ea538ca
```

**Comment by gramasaurous** [comment]
I was able to get the feature enabled:

<img width="721" alt="screen shot 2017-08-24 at 1 49 47 pm" src="https://user-images.githubusercontent.com/2685601/29692595-caf2a626-88e5-11e7-998c-d50792d1817e.png">

But I see some questionable logs when I fire up a video:

```
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/plexmediaserver/dri/nouveau_drv_video.so
libva info: va_openDriver() returns -1
```

**Comment by cturra** [comment]
closing since this project is now deprecated.
