### ISSUE TITLE
Fetch latest public

### ISSUE THREAD

**Issue by paulroche** [cturra/docker-plexmediaserver#7]
curl -s https://plex.tv/downloads | awk '/deb/ && /64-bit/' | sed "s/._href=\"([^\"]_\.deb)\"[^>]_>._/\1/"

:minibus:

**Comment by cturra** [comment]
now included in the `startup.sh` script :dancers: 

https://github.com/cturra/docker-plexmediaserver/blob/master/assets/scripts/startup.sh
